version: '2'

networks: 
    airline:

services: 
    cli:
        container_name: cli
        image: hyperledger/fabric-tools:$IMAGE_TAG
        tty: true
        stdin_open: true
        command: /bin/bash
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        environment: 
            - GOPATH=/opt/gopath
            - ORDERER_ADDRESS=orderer.acme.com:7050
            - CORE_PEER_ID=cli
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_ADDRESS=peer0.acme.com:7051
            - CORE_PEER_TLS_ENABLED=false
            # - CORE_PEER_MSPID=AcmeMSP
            - CORE_PEER_LOCALMSPID=AcmeMSP
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/acme.com/users/Admin@acme.com/msp
        volumes: 
            - /var/run/:/host/var/run/
            - /home/varun/go_projects/src/github.com/vn2699/hyp/chaincode4/main.go:/opt/gopath/src/github.com/chaincode/main.go
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
            - ./network-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/network-config
        networks: 
            - airline