version: '2'

services: 

    couchdb.peer0.acme.com:
        image: hyperledger/fabric-couchdb
        command: couchdb
        ports:
            - 5984:5984
    
    couchdb.peer0.budget.com:
        image: hyperledger/fabric-couchdb
        command: couchdb
        ports:
            - 7984:5984
    
    couchdb.peer0.expo.com:
        image: hyperledger/fabric-couchdb
        command: couchdb
        ports:
            - 9984:5984