version: '2'

networks: 
    airline:

volumes: 

    zookeepeer0:
    zookeepeer1:
    zookeepeer2:

    kafka0:
    kafka1:
    kafka2:
    kafka3:

    data.orderer0.acme.com:
    data.orderer1.acme.com:
    data.orderer2.acme.com:
    couchdb.peer0.acme.com:
    couchdb.peer0.budget.com:
    couchdb.peer0.expo.com:
    data.peer0.acme.com:
    data.peer0.budget.com:
    data.peer0.expo.com:

services:

    zookeeper0:
        container_name: zookeepeer0
        extends: 
            file: ./docker-compose-zooka.yaml
            service: zookeeper
        environment: 
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=zookeepeer0:2888:3888 server.2=zookeepeer1:2888:3888 server.3=zookeepeer2:2888:3888
        networks: 
            - airline

    zookeeper1:
        container_name: zookeepeer1
        extends: 
            file: ./docker-compose-zooka.yaml
            service: zookeeper
        environment: 
            - ZOO_MY_ID=2
            - ZOO_SERVERS=server.1=zookeepeer0:2888:3888 server.2=zookeepeer1:2888:3888 server.3=zookeepeer2:2888:3888
        networks: 
            - airline

    zookeeper2:
        container_name: zookeepeer2
        extends: 
            file: ./docker-compose-zooka.yaml
            service: zookeeper
        environment: 
            - ZOO_MY_ID=3
            - ZOO_SERVERS=server.1=zookeepeer0:2888:3888 server.2=zookeepeer1:2888:3888 server.3=zookeepeer2:2888:3888
        networks: 
            - airline
    
    kafka0:
        extends: 
            file: ./docker-compose-zooka.yaml
            service: kafka
        environment: 
            - KAFKA_BROKER_ID=0
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_MESSAGE_MAX_BYTES=2147483647
            - KAFKA_REPLICA_FETCH_MAX_BYTES=2147483647
            - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=2147483647
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
        networks:
            - airline

    kafka1:
        extends: 
            file: ./docker-compose-zooka.yaml
            service: kafka
        environment: 
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_MESSAGE_MAX_BYTES=2147483647
            - KAFKA_REPLICA_FETCH_MAX_BYTES=2147483647
            - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=2147483647
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
        networks:
            - airline

    kafka2:
        extends: 
            file: ./docker-compose-zooka.yaml
            service: kafka
        environment: 
            - KAFKA_BROKER_ID=2
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_MESSAGE_MAX_BYTES=2147483647
            - KAFKA_REPLICA_FETCH_MAX_BYTES=2147483647
            - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=2147483647
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
        networks:
            - airline

    kafka3:
        extends: 
            file: ./docker-compose-zooka.yaml
            service: kafka
        environment: 
            - KAFKA_BROKER_ID=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_MESSAGE_MAX_BYTES=2147483647
            - KAFKA_REPLICA_FETCH_MAX_BYTES=2147483647
            - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=2147483647
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
        networks:
            - airline

    orderer0.acme.com:
        container_name: orderer0.acme.com
        extends: 
            file: ./docker-compose-base.yaml
            service: orderer.acme.com
        environment: 
            - ORDERER_HOST=orderer0.acme.com
            - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
            - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
            - ORDERER_KAFKA_RETRY_LONGINTERVAL=30s
            - ORDERER_KAFKA_RETRY_LONGTOTAL=5m
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
        volumes:
            - ./network-config/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ./crypto-config/ordererOrganizations/acme.com/orderers/orderer0.acme.com/msp:/var/hyperledger/msp
            - ./crypto-config/ordererOrganizations/acme.com/orderers/orderer0.acme.com/tls:/var/hyperledger/tls
            - ./crypto-config/peerOrganizations/acme.com/:/var/hyperledger/acme
            - ./crypto-config/peerOrganizations/budget.com/:/var/hyperledger/budget
            - data.orderer0.acme.com:/var/ledger
        ports:
            - 7050:7050
        networks: 
            - airline
    
    orderer1.acme.com:
        container_name: orderer1.acme.com
        extends: 
            file: ./docker-compose-base.yaml
            service: orderer.acme.com
        environment: 
            - ORDERER_HOST=orderer1.acme.com
            - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
            - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
            - ORDERER_KAFKA_RETRY_LONGINTERVAL=30s
            - ORDERER_KAFKA_RETRY_LONGTOTAL=5m
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
        volumes:
            - ./network-config/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ./crypto-config/ordererOrganizations/acme.com/orderers/orderer1.acme.com/msp:/var/hyperledger/msp
            - ./crypto-config/ordererOrganizations/acme.com/orderers/orderer1.acme.com/tls:/var/hyperledger/tls
            - ./crypto-config/peerOrganizations/acme.com/:/var/hyperledger/acme
            - ./crypto-config/peerOrganizations/budget.com/:/var/hyperledger/budget
            - data.orderer1.acme.com:/var/ledger
        ports:
            - 8050:8050
        networks: 
            - airline

    orderer2.acme.com:
        container_name: orderer2.acme.com
        extends: 
            file: ./docker-compose-base.yaml
            service: orderer.acme.com
        environment: 
            - ORDERER_HOST=orderer2.acme.com
            - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
            - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
            - ORDERER_KAFKA_RETRY_LONGINTERVAL=30s
            - ORDERER_KAFKA_RETRY_LONGTOTAL=5m
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
        volumes:
            - ./network-config/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ./crypto-config/ordererOrganizations/acme.com/orderers/orderer2.acme.com/msp:/var/hyperledger/msp
            - ./crypto-config/ordererOrganizations/acme.com/orderers/orderer2.acme.com/tls:/var/hyperledger/tls
            - ./crypto-config/peerOrganizations/acme.com/:/var/hyperledger/acme
            - ./crypto-config/peerOrganizations/budget.com/:/var/hyperledger/budget
            - data.orderer2.acme.com:/var/ledger
        ports:
            - 9050:9050
        networks: 
            - airline
    
    couchdb.peer0.acme.com:
        container_name: couchdb.peer0.acme.com
        extends: 
            file: ./docker-compose-couchdb.yaml
            service: couchdb.peer0.acme.com
        environment: 
            - COUCHDB_USER=rahul
            - COUCHDB_PASSWORD=pw
        ports:
            - 5984:5984
        networks: 
            - airline

    peer0.acme.com:
        container_name: peer0.acme.com
        extends: 
            file: ./docker-compose-base.yaml
            service: peer.base
        environment: 
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_ID=peer0.acme.com
            - CORE_PEER_NETWORKID=dev
            - CORE_PEER_ADDRESS=peer0.acme.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.acme.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.acme.com:7051
            - CORE_PEER_LOCALMSPID=AcmeMSP
            - CORE_PEER_AUTODETECT=true
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            # - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            # - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            # - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            # - CORE_PEER_TLS_CLIENTROOTCAS=
            # - CORE_PEER_TLS_CLIENTKEY_FILE=
            # - CORE_PEER_TLS_CLIENTCERT_FILE=
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.acme.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_REQUESTTIMEOUT=1000s
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=rahul
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pw
            - CORE_PEER_FILESYSYTEMPATH=/var/hyperledger/production
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
        volumes: 
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/acme.com/peers/peer0.acme.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/acme.com/peers/peer0.acme.com/tls:/etc/hyperledger/fabric/tls
        - data.peer0.acme.com:/var/hyperledger/production
        ports:
            - 7051:7051
            - 7052:7052
        depends_on: 
            - orderer0.acme.com
            - orderer1.acme.com
            - orderer2.acme.com
            - couchdb.peer0.acme.com
        networks: 
            - airline
    
    couchdb.peer0.budget.com:
        container_name: couchdb.peer0.budget.com
        extends:
            file: ./docker-compose-couchdb.yaml
            service: couchdb.peer0.budget.com
        environment: 
            - COUCHDB_USER=varun
            - COUCHDB_PASSWORD=pw
        ports:
            - 7984:5984
        networks: 
            - airline

    peer0.budget.com:
        container_name: peer0.budget.com
        extends: 
            file: ./docker-compose-base.yaml
            service: peer.base
        environment: 
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_PEER_LISTENADDRES=0.0.0.0:8051
            - CORE_PEER_ID=peer0.budget.com
            - CORE_PEER_NETWORKID=dev
            - CORE_PEER_ADDRESS=peer0.budget.com:8051
            - CORE_PEER_LOCALMSPID=BudgetMSP
            - CORE_PEER_AUTODETECT=true
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.budget.com:8051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.budget.com:8051
            # - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            # - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            # - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            # - CORE_PEER_TLS_CLIENTROOTCAS=
            # - CORE_PEER_TLS_CLIENTKEY_FILE=
            # - CORE_PEER_TLS_CLIENTCERT_FILE=
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=varun
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pw
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.budget.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_REQUESTTIMEOUT=1000s
            - CORE_PEER_FILESYSYTEMPATH=/var/hyperledger/production
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
        volumes: 
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/budget.com/peers/peer0.budget.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/budget.com/peers/peer0.budget.com/tls:/etc/hyperledger/fabric/tls
        - data.peer0.budget.com:/var/hyperledger/production
        ports:
            - 8051:8051
            - 8052:8052
        depends_on: 
            - orderer0.acme.com
            - orderer1.acme.com
            - orderer2.acme.com
            - couchdb.peer0.budget.com
        networks: 
            - airline

    couchdb.peer0.expo.com:
        container_name: couchdb.peer0.expo.com
        extends: 
            file: ./docker-compose-couchdb.yaml
            service: couchdb.peer0.expo.com
        environment: 
            - COUCHDB_USER=anil
            - COUCHDB_PASSWORD=pw
        ports:
            - 9984:5984
        networks: 
            - airline

    peer0.expo.com:
        container_name: peer0.expo.com
        extends: 
            file: ./docker-compose-base.yaml
            service: peer.base
        environment: 
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_ID=peer0.expo.com
            - CORE_PEER_NETWORKID=dev
            - CORE_PEER_ADDRESS=peer0.expo.com:9051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.expo.com:9051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.expo.com:9051
            - CORE_PEER_LOCALMSPID=ExpoMSP
            - CORE_PEER_AUTODETECT=true
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            # - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            # - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            # - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            # - CORE_PEER_TLS_CLIENTROOTCAS=
            # - CORE_PEER_TLS_CLIENTKEY_FILE=
            # - CORE_PEER_TLS_CLIENTCERT_FILE=
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.expo.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_REQUESTTIMEOUT=1000s
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=anil
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pw
            - CORE_PEER_FILESYSYTEMPATH=/var/hyperledger/production
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
        volumes: 
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/expo.com/peers/peer0.expo.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/expo.com/peers/peer0.expo.com/tls:/etc/hyperledger/fabric/tls
        - data.peer0.expo.com:/var/hyperledger/production
        ports:
            - 9051:9051
            - 9052:9052
        depends_on: 
            - orderer0.acme.com
            - orderer1.acme.com
            - orderer2.acme.com
            - couchdb.peer0.expo.com
        networks: 
            - airline

    cli:
        container_name: cli
        image: hyperledger/fabric-tools:$IMAGE_TAG
        tty: true
        stdin_open: true
        dns_search: .
        command: /bin/bash
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        environment: 
            - GOPATH=/opt/gopath
            - ORDERER_ADDRESS=orderer.acme.com:7050
            - CORE_PEER_ID=cli
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_ADDRESS=peer0.acme.com:7051
            - CORE_PEER_TLS_ENABLED=false
            # - CORE_PEER_MSPID=AcmeMSP
            - CORE_PEER_LOCALMSPID=AcmeMSP
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/acme.com/users/Admin@acme.com/msp
        volumes: 
            - /var/run/:/host/var/run/
            - /home/varun/Documents/projects/Hyperledger/hyp-ex2/chaincode/main.go:/opt/gopath/src/github.com/chaincode/main.go
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
            - ./network-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/network-config
        networks: 
            - airline